baseURL = 'https://pea53.com/'
languageCode = 'en-us'
title = 'Pea53'
theme = 'hyde'

[params]
  themeColor = "theme-base-0d"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    guessSyntax = false
    tabWidth = 2
    style = 'catppuccin-latte'
